#!/usr/bin/env python3
"""Generative .codex/skills mirror of the canonical .claude/skills tree.

Canonical source: .claude/skills  (humans edit ONLY here).
Generated output: .codex/skills    (committed, NEVER hand-edited).

The mirror excludes Codex-native or Claude-only helper skills listed in
EXCLUDE_TOP_LEVEL. For mirrored files, the only content transform is a
path-string rewrite inside TEXT files:
    ".claude/skills"  ->  ".codex/skills"
Binary assets (fonts/images) are copied byte-for-byte.

Usage:
    python3 sync_codex_mirror.py           # regenerate .codex/skills
    python3 sync_codex_mirror.py --check    # exit 1 if mirror is stale

NOTE: SRC/DST below are built from SEPARATE path components (".claude","skills")
on purpose — NOT the joined literal ".claude/skills". The mirror's blunt string
replace targets ".claude/skills"; keeping the components separate means the
mirrored copy of THIS script still points SRC=.claude, DST=.codex and stays
correct when run from either tree.
"""
from __future__ import annotations
import shutil
import sys
import tempfile
import time
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[5]  # depth: dev/scripts/slide/skills/.claude/repo
SRC = REPO_ROOT / ".claude" / "skills"
DST = REPO_ROOT / ".codex" / "skills"

# Built from separate components for the SAME reason as SRC/DST below: the
# blunt replace targets the joined literal ".claude/skills", so keeping the
# literal un-joined here means OLD/NEW survive intact in the mirrored copy of
# this script (mirrored OLD == ".claude/skills", NEW == ".codex/skills").
_CLAUDE = ".claude"
_CODEX = ".codex"
OLD = _CLAUDE + "/skills"
NEW = _CODEX + "/skills"

TEXT_SUFFIXES = {".md", ".py", ".sh", ".mjs", ".js", ".json",
                 ".css", ".html", ".txt", ".csv", ".svg", ".yml", ".yaml"}
EXCLUDE_DIRS = {"__pycache__", "node_modules", ".venv", ".git", ".pytest_cache"}
EXCLUDE_SUFFIXES = {".pyc"}
EXCLUDE_NAMES = {".DS_Store", "_GENERATED.md"}  # marker is synthesized, not mirrored content → keep out of the drift comparison
EXCLUDE_TOP_LEVEL = {
    "codex-image",    # Codex uses its built-in imagegen/image_gen skill instead.
    "huashu-design",  # Claude-only design reference (upstream provenance) — not part of the PPTX pipeline.
}

# f-string over OLD (not a literal ".claude/skills") so the marker is
# copy-INDEPENDENT: both the canonical and the mirrored sync evaluate {OLD} to
# ".claude/skills", producing an identical _GENERATED.md. A literal here would be
# rewritten to ".codex/skills" in the mirror, making the .codex-side --check see
# a phantom drift on _GENERATED.md and hard-fail every Codex gate.
GENERATED_MARKER = f"""# GENERATED — DO NOT EDIT

This tree is generated by
`{OLD}/slide/scripts/dev/sync_codex_mirror.py` from the canonical
`{OLD}`. Edit there, then regenerate:

    python3 {OLD}/slide/scripts/dev/sync_codex_mirror.py

Hand-edits here are overwritten and fail the drift-check
(`sync_codex_mirror.py --check`) in the quality gate.
"""


def _iter_files(root: Path, *, exclude_top_level: bool = True):
    for p in sorted(root.rglob("*")):
        rel_parts = p.relative_to(root).parts
        if exclude_top_level and rel_parts and rel_parts[0] in EXCLUDE_TOP_LEVEL:
            continue
        if any(part in EXCLUDE_DIRS for part in rel_parts):
            continue
        if p.is_dir():
            continue
        if p.name in EXCLUDE_NAMES or p.suffix in EXCLUDE_SUFFIXES:
            continue
        yield p


def _transform(path: Path, data: bytes) -> bytes:
    if path.suffix.lower() in TEXT_SUFFIXES:
        try:
            return data.decode("utf-8").replace(OLD, NEW).encode("utf-8")
        except UnicodeDecodeError:
            return data
    return data


def _rmtree_with_retry(path: Path) -> None:
    # Windows can briefly hold read handles from git/indexers while tests or
    # agents inspect .codex. Retry before surfacing a real stale lock.
    last_error = None
    for _ in range(10):
        try:
            shutil.rmtree(path)
            return
        except PermissionError as e:
            last_error = e
            time.sleep(0.5)
    if last_error:
        raise last_error


def generate(dst: Path) -> int:
    if dst.exists():
        _rmtree_with_retry(dst)
    dst.mkdir(parents=True)
    # write_bytes (not write_text) to avoid Windows \n->\r\n translation, so the
    # marker stays LF like every other mirrored file (no perpetual git "modified").
    (dst / "_GENERATED.md").write_bytes(GENERATED_MARKER.encode("utf-8"))
    count = 1
    for src_file in _iter_files(SRC):
        out = dst / src_file.relative_to(SRC)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_bytes(_transform(src_file, src_file.read_bytes()))
        count += 1
    return count


def check() -> int:
    with tempfile.TemporaryDirectory() as tmp:
        ref = Path(tmp) / "skills"
        generate(ref)
        ref_files = {p.relative_to(ref) for p in _iter_files(ref, exclude_top_level=False)}
        dst_files = (
            {p.relative_to(DST) for p in _iter_files(DST, exclude_top_level=False)}
            if DST.exists() else set()
        )
        stale = []
        for rel in sorted(ref_files | dst_files):
            a, b = ref / rel, DST / rel
            if not a.exists() or not b.exists() or a.read_bytes() != b.read_bytes():
                stale.append(rel)
        if stale:
            sys.stderr.write("[x] .codex/skills mirror is STALE:\n")
            for rel in stale:
                sys.stderr.write(f"    {rel.as_posix()}\n")
            sys.stderr.write(
                "\nRegenerate:\n"
                "    python3 .claude/skills/slide/scripts/dev/sync_codex_mirror.py\n"
            )
            return 1
    print(f"[ok] .codex/skills mirror is in sync ({len(ref_files)} files)")
    return 0


def main(argv: list[str]) -> int:
    if "--check" in argv:
        return check()
    n = generate(DST)
    print(f"[ok] Regenerated .codex/skills ({n} files) from .claude/skills")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
